# Hira — Mosquitto MQTT Broker
# Autenticación obligatoria: se rechazan conexiones anónimas (V-01)

listener 1883
allow_anonymous false
password_file /mosquitto/config/passwd

# Persistencia
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest file /mosquitto/log/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information
